### ISSUE TITLE
Latest sqlalchemy version 2.0.28 causes script to crash on async_engine

### ISSUE THREAD

**Issue by lucianosrp** [firebolt-db/firebolt-sqlalchemy#96]
SQLAlchemy `2.0.28` introduces a change on asyncio that will raise an error when `QueuePool`  is used on `create_async_engine()` 

- Error details can be found [here](https://docs.sqlalchemy.org/en/20/errors.html#pool-class-cannot-be-used-with-asyncio-engine-or-vice-versa)
- Changes on SQLAlchemy source code [here](https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5169/3/lib/sqlalchemy/engine/create.py)

I am not entierely sure how this relates to the Async Dialect and I didn't find quick ways to fix this.

## Replication

I justed run AsyncIO example on the README.md with `sqlalchemy==2.0.28`

It raises: 

```bash
Pool class QueuePool cannot be used with asyncio engine
```

I would suggest setting the dialect requirements to `sqlalchemy<=2.0.26`

**Comment by ptiurin** [comment]
Thank you for reporting this @lucianosrp ! I believe I have a fix for this (in the linked PR) and will aim to release it soon.

**Comment by lucianosrp** [comment]
That's great! Thanks for looking into this.
